### ISSUE TITLE
Issue using Graph type definition in Angular

### ISSUE THREAD

**Issue by phoenixchinar** [tmont/tarjan-graph#4]
In file [index.d.ts](https://github.com/tmont/tarjan-graph/blob/bf8b8e7330efbc6d409b5360f0a300ad921186bb/index.d.ts#L26) the export in the type definition should be updated to:
```
export = Graph;
```

instead of

```
export {
	Graph
}

```
This brings it inline with the actual export being done in index.js. I have an angular application that fails to compile due to this, or gets a runtime error (depending on the import).

I'd be happy to open a pull request if that helps.

**Comment by phoenixchinar** [comment]
Resolved by updating typescript function.

**Comment by CharlesIrvineKC** [comment]
I am having the same problem. Can you provide a more information on how you resolved the issue? Thanks
