### ISSUE TITLE
Getting Webpack error on "new Graph() in ts file

### ISSUE THREAD

**Issue by CharlesIrvineKC** [tmont/tarjan-graph#5]
I'm getting a web pack error when trying to use with an Angular application:

```
TypeError: tarjan_graph__WEBPACK_IMPORTED_MODULE_7__.Graph is not a constructor
```

My code is:

```
import { Graph } from 'tarjan-graph';

createTarganGraph(topics: Topic[]): Graph {
        const graph = new Graph();
        topics.forEach(t => graph.add(t.name, t.prereqs.map(p => p.topic_name)));
        return graph;
    }
```

Any ideas what I might be doing wrong?

Thanks

**Comment by sinna94** [comment]
I have the same problem
Did you find a solution?

**Comment by mrkev** [comment]
The type definitions seem to be wrong. The correct way to do it is importing the default, not `Graph`, as opposed to what TS says:
```typescript
// This is what TS wants, but not how the code looks
import { Graph } from 'tarjan-graph';
// This would work
import Graph from 'tarjan-graph';
```

**Comment by tmont** [comment]
Sorry for my extreme laziness about not fixing this. I've ported this library to TypeScript and everything should be fixed. It is however a breaking change as the default export changed, so take caution and pin the version in your `package.json`. See [this comment](https://github.com/tmont/tarjan-graph/pull/6#issuecomment-1026204403) for more details.

Well, it's really the same amount of details, but whatever.
